# Root app stack. Merges with infra/databases/docker-compose.yml at runtime.
name: data-bridge

services:
  databridge-app:
    build:
      context: .              # repo root (Dockerfile + pom.xml)
      dockerfile: Dockerfile
    container_name: databridge-app
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker

      BRIDGE_SOURCE_TYPE: oracle
      BRIDGE_SOURCE_JDBC_URL: jdbc:oracle:thin:@source-db:1521/XEPDB1
      BRIDGE_SOURCE_USERNAME: DATAANALYTIC
      BRIDGE_SOURCE_PASSWORD: oracle

      BRIDGE_TARGET_TYPE: postgres
      BRIDGE_TARGET_JDBC_URL: jdbc:postgresql://target-db:5432/data_analytic_target
      BRIDGE_TARGET_USERNAME: postgres
      BRIDGE_TARGET_PASSWORD: postgres

      BRIDGE_METADATA_TYPE: postgres
      BRIDGE_METADATA_JDBC_URL: jdbc:postgresql://metadata-db:5432/data_analytic_batch
      BRIDGE_METADATA_USERNAME: postgres
      BRIDGE_METADATA_PASSWORD: postgres

      BRIDGE_STATE_STORE_URI: mongodb://root:root@state-store:27017/dataAnalytic?authSource=admin

      SERVER_PORT: "8081"
      JAVA_OPTS: ""
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "5"
    depends_on:
      postgres-target:
        condition: service_healthy
      postgres-batch:
        condition: service_healthy
      mongo-storage:
        condition: service_healthy
      oracle-source:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ./amazon_categories.csv:/data/csv/amazon_categories.csv:ro
      - ./amazon_products.csv:/data/csv/amazon_products.csv:ro
